//pages
export const PAGE_MAIN='MAIN';
export const PAGE_BASKETS_EXPLORER='BASKETS_EXPLORER';
export const PAGE_VIEW_BASKET='VIEW_BASKET';
export const PAGE_VIEW_LOAN='VIEW_LOAN';

//dialogs
export const DEPOSIT_DIALOG='DEPOSIT_DIALOG';
export const PAYMENT_DIALOG='PAYMENT_DIALOG';
export const TAKE_LOAN_DIALOG='TAKE_LOAN_DIALOG';
export const CREATE_BASKET_DIALOG='CREATE_BASKET_DIALOG';

//contract addresses
export const LENDING_CONTRACT_ADDRESS='0xdd3fed9427e688a80a426b206cA9c176A864ad89';

//jobs
export const CREATING_BASKET_JOB='CREATING_BASKET_JOB';
export const DEPOSITING_LIQUIDITY_JOB='DEPOSITING_LIQUIDITY_JOB';
export const TAKEING_LOAN_JOB='TAKEING_LOAN_JOB';